---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: my-global-peer
spec:
  peerIP: 192.168.88.1
  asNumber: 64555

---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: metal-lb
spec:
  cidr: 192.168.100.0/24
  ipipMode: Never
  natOutgoing: true
  disabled: false
  nodeSelector: all()