apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      values: |
        injector:
          enabled: false
        global:
          ingress:
            enabled: true
            hosts:
              - host: vault.laba.local
                paths:
                  - /
        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              config: |
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  }

                  ui = true
                  
                  storage "raft" {
                  path = "/vault/data"
                    retry_join {
                    leader_api_addr = "http://hashicorp-vault-0.hashicorp-vault-internal:8200"
                  }
                    retry_join {
                    leader_api_addr = "http://hashicorp-vault-1.hashicorp-vault-internal:8200"
                  }
                    retry_join {
                    leader_api_addr = "http://hashicorp-vault-s.hashicorp-vault-internal:8200"
                  }
                  }
                  service_registration "kubernetes" {}

          dataStorage:
            enabled: true
            storageClass: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ui:
            enabled: true
            serviceType: clusterIP
          agent:
            enabled: false



  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
